### ISSUE TITLE
Apply to any duplicate file name

### ISSUE THREAD

**Issue by nikordaris** [Connormiha/atom-tab-foldername-index#2]
Instead of only renaming it for index.js can it rename it for any duplicate file names that are open? In my react components i also name my styles the same in each folder so i would like those to also include the folder name. If detecting duplicate file names is non-trivial, what about just doing it for all files?

**Comment by Connormiha** [comment]
I thought about it. I will add support of these cases in next major release. I thought about it. I will add support of these cases in next major release.

**Comment by JuliaSklyar** [comment]
Or at least it could be handy if we could configure file names, which we want to have double titles (Folder + file name).

**Comment by Connormiha** [comment]
@JuliaSklyar yes, it is possible in future version.

**Comment by JuliaSklyar** [comment]
Thanks!
