### ISSUE TITLE
Tab is not colored with VCS status

### ISSUE THREAD

**Issue by iagoqo** [Connormiha/atom-tab-foldername-index#9]
Atom version: 1.34.0
Package version: 3.3.0

Atom's Tab package changes the color of tab names depending on the VCS status:
![image](https://user-images.githubusercontent.com/1913495/53894008-38103800-4027-11e9-92ba-bebc2f6c49fc.png)

When this package is enabled the tab text does not change color:
![image](https://user-images.githubusercontent.com/1913495/53894024-4199a000-4027-11e9-9567-5d9cf1681a93.png)

**Comment by Connormiha** [comment]
@iagoqo  Thanks for your issue. It will be fixed in next release soon.

**Comment by Connormiha** [comment]
Fixed in 3.3.1
